"""SUPPLIERS — SYNTHETIC (see docs/data-plan.md § B. Supplier information):
Open Supply Hub has real facility identities but its API requires a token this
environment doesn't have (401 on every unauthenticated call — recorded in
dataset_registry.yaml), and no public source publishes supplier
capacity/cost/lead-time/reliability at all (commercially sensitive by nature).

Every value below is generated by a seeded, documented, parametric process —
reproducible (same seed -> same roster), not claimed real, and tagged
`Provenance.SYNTHETIC` on every row. Regions are chosen to match the
platform's demo scenarios (a China supplier that goes DISRUPTED for the Suez
story, India/Vietnam alternatives the Sourcing Agent can shift volume to).
"""
from __future__ import annotations

import numpy as np
import pandas as pd

SEED = 42

_ROSTER = [
    # (supplier_id, name, region, base_status, base_risk)
    ("S001", "Chengdu Precision Components", "China", "DISRUPTED", "HIGH"),
    ("S002", "Shenzhen Circuit Works", "China", "REDUCED", "HIGH"),
    ("S003", "Pune Industrial Fabricators", "India", "ACTIVE", "LOW"),
    ("S004", "Chennai Component Systems", "India", "ACTIVE", "LOW"),
    ("S005", "Hanoi Assembly Group", "Vietnam", "ACTIVE", "MEDIUM"),
    ("S006", "Ho Chi Minh Precision Ltd", "Vietnam", "ACTIVE", "MEDIUM"),
    ("S007", "Istanbul Trade Manufacturing", "Turkey", "ACTIVE", "MEDIUM"),
    ("S008", "Rotterdam Regional Supply", "Netherlands", "ACTIVE", "LOW"),
]

# Real product_ids (UCI Online Retail StockCodes), not placeholder "P001"-style
# IDs — picked to match the 3 highest-volume products among the 40 series
# ml/training selects for forecasting (see ml/training/prepare_modeling_data.py),
# so the Sourcing Agent's suppliers, the Inventory Agent's forecasts, and the
# Logistics Agent's shipments can all be reasoned about for the SAME real
# products once the Optimization Engine (Phase 10) needs to join them. An
# earlier version of this module used "P001"/"P002"/"P003", which had zero
# overlap with every other agent's product_id space — caught while starting
# Phase 8, fixed here rather than carried forward.
_PRODUCTS = ["23166", "22197", "84077"]


def synthesize_suppliers(seed: int = SEED) -> tuple[pd.DataFrame, dict]:
    rng = np.random.default_rng(seed)
    rows = []
    for supplier_id, name, region, status, risk in _ROSTER:
        for product_id in _PRODUCTS:
            if rng.random() < 0.35:  # not every supplier carries every product
                continue
            base_capacity = {"China": 10000, "India": 8000, "Vietnam": 6000, "Turkey": 5000, "Netherlands": 4000}[region]
            capacity = 0 if status == "DISRUPTED" else int(base_capacity * rng.uniform(0.6, 1.1))
            unit_cost = round(float(rng.uniform(85, 120)), 2)
            lead_time = int(rng.integers(4, 12))
            reliability = round(float(rng.uniform(0.75, 0.99)) if status == "ACTIVE" else float(rng.uniform(0.3, 0.7)), 2)

            rows.append(
                {
                    "supplier_id": supplier_id,
                    "supplier_name": name,
                    "region": region,
                    "product_id": product_id,
                    "capacity": capacity,
                    "unit_cost": unit_cost,
                    "lead_time_days": lead_time,
                    "reliability": reliability,
                    "risk_level": risk,
                    "status": status,
                    "provenance": "synthetic",
                }
            )

    out = pd.DataFrame(rows)
    report = {
        "output_rows": len(out),
        "seed": seed,
        "unique_suppliers": out["supplier_id"].nunique(),
        "unique_products": out["product_id"].nunique(),
    }
    return out, report
