-- ResilientSC schema for hana: state + reference tables.
-- Generated by `python -m backend.database.ddl`; do not edit - change the table definitions and regenerate.

CREATE TABLE world_states (
	simulation_id NVARCHAR(64) NOT NULL,
	scenario_type NVARCHAR(64) NOT NULL,
	status NVARCHAR(32) NOT NULL,
	version INTEGER NOT NULL,
	created_at NVARCHAR(40) NOT NULL,
	updated_at NVARCHAR(40) NOT NULL,
	state_json NCLOB NOT NULL,
	initial_state_json NCLOB NOT NULL,
	PRIMARY KEY (simulation_id)
);

CREATE INDEX ix_world_states_status ON world_states (status);

CREATE INDEX ix_world_states_updated_at ON world_states (updated_at);

CREATE TABLE world_state_checkpoints (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	simulation_id NVARCHAR(64) NOT NULL,
	version INTEGER NOT NULL,
	checkpoint NVARCHAR(64) NOT NULL,
	actor NVARCHAR(256) NOT NULL,
	at NVARCHAR(40) NOT NULL,
	changed_fields NCLOB NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(simulation_id) REFERENCES world_states (simulation_id)
);

CREATE INDEX ix_world_state_checkpoints_simulation_id ON world_state_checkpoints (simulation_id);

CREATE TABLE ref_demand_panel (
	date DATE,
	product_id NVARCHAR(32),
	location_id NVARCHAR(64),
	demand_quantity INTEGER,
	rolling_mean_28 DOUBLE,
	split NVARCHAR(16)
);

CREATE TABLE ref_disruptions (
	event_id NVARCHAR(64),
	event_type NVARCHAR(64),
	location NVARCHAR(255),
	start_date TIMESTAMP,
	end_date TIMESTAMP,
	severity NVARCHAR(16),
	affected_route NVARCHAR(64),
	affected_supplier NVARCHAR(64),
	estimated_delay_days DOUBLE,
	status NVARCHAR(16)
);

CREATE TABLE ref_inventory (
	warehouse_id NVARCHAR(64),
	product_id NVARCHAR(32),
	date DATE,
	opening_stock INTEGER,
	inbound_quantity INTEGER,
	outbound_quantity INTEGER,
	closing_stock INTEGER,
	safety_stock INTEGER,
	stockout_flag BOOLEAN,
	provenance NVARCHAR(32)
);

CREATE TABLE ref_routes (
	route_id NVARCHAR(64),
	origin NVARCHAR(64),
	destination NVARCHAR(64),
	transport_mode NVARCHAR(16),
	distance_km DOUBLE,
	capacity INTEGER,
	transit_time_days DOUBLE,
	cost_per_unit DOUBLE,
	status NVARCHAR(16),
	provenance NVARCHAR(32)
);

CREATE TABLE ref_suppliers (
	supplier_id NVARCHAR(32),
	supplier_name NVARCHAR(128),
	region NVARCHAR(64),
	product_id NVARCHAR(32),
	capacity INTEGER,
	unit_cost DOUBLE,
	lead_time_days INTEGER,
	reliability DOUBLE,
	risk_level NVARCHAR(16),
	status NVARCHAR(16),
	provenance NVARCHAR(32)
);

CREATE TABLE ref_tariffs (
	origin_country NVARCHAR(8),
	destination_country NVARCHAR(8),
	product_category NVARCHAR(32),
	effective_year INTEGER,
	tariff_rate DOUBLE,
	is_country_level_proxy BOOLEAN
);
