-- TEARDOWN of the 17 core tables. Generated by `python -m backend.database.hana_core`; do not edit. Change hana_core_spec.py and regenerate.
--
-- DESTRUCTIVE: drops the tables and every row in them, in the CURRENT schema. Nothing in this repository runs it.
-- Children first, so no foreign key blocks a drop. Check `SELECT CURRENT_SCHEMA FROM DUMMY;` before running.

DROP TABLE "DEMAND_MODELING_PANEL";
DROP TABLE "DEMAND";
DROP TABLE "INVENTORY";
DROP TABLE "INVENTORY_POLICY";
DROP TABLE "SCENARIO_PARAM";
DROP TABLE "SCENARIO_STATE";
DROP TABLE "SCENARIO";
DROP TABLE "DISRUPTION_IMPACT";
DROP TABLE "DISRUPTION_EVENT";
DROP TABLE "TARIFF";
DROP TABLE "ROUTE";
DROP TABLE "SUPPLIER_PRODUCT";
DROP TABLE "SUPPLIER";
DROP TABLE "WAREHOUSE";
DROP TABLE "PRODUCT";
DROP TABLE "PORT";
DROP TABLE "COUNTRY";
