"""The database schema as SQL, for a database where the application may not create its own tables.

    python -m backend.database.ddl --dialect hana                  print DDL for SAP HANA Cloud
    python -m backend.database.ddl --dialect hana --schema RSC     ...qualified with a schema
    python -m backend.database.ddl --include state                 only the world-state tables
    python -m backend.database.ddl --write db/hana/schema.sql      what is checked in

The HANA dialect needs `pip install -r requirements-sap.txt`. The output is generated from the same table
definitions the application uses, so it cannot drift from them; a test compares the checked-in file with a fresh
render whenever the dialect is installed.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from sqlalchemy import MetaData
from sqlalchemy.schema import CreateIndex, CreateTable

from backend.data.datasets import metadata as reference_metadata
from backend.database.world_state_repository import metadata as state_metadata

GROUPS = {"state": state_metadata, "reference": reference_metadata}


def _dialect(name: str):
    if name == "sqlite":
        from sqlalchemy.dialects import sqlite
        return sqlite.dialect()
    if name == "hana":
        try:
            from sqlalchemy_hana.dialect import HANAHDBCLIDialect
        except ImportError as exc:  # pragma: no cover - depends on the environment
            raise SystemExit("the HANA dialect is not installed: pip install -r requirements-sap.txt") from exc
        return HANAHDBCLIDialect()
    raise SystemExit(f"unknown dialect {name!r}; use sqlite or hana")


def statements(dialect_name: str, *, schema: str | None = None, include: tuple[str, ...] = ("state", "reference")) -> list[str]:
    dialect = _dialect(dialect_name)
    out: list[str] = []
    for group in include:
        source = GROUPS[group]
        target = MetaData()
        for table in source.sorted_tables:  # dependency order: a referenced table before the table that references it
            table.to_metadata(target, schema=schema)
        for table in target.sorted_tables:
            out.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
            out.extend(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";" for index in sorted(table.indexes, key=lambda i: i.name or ""))
    return out


def render(dialect_name: str, *, schema: str | None = None, include: tuple[str, ...] = ("state", "reference")) -> str:
    header = (
        f"-- ResilientSC schema for {dialect_name}{f', schema {schema}' if schema else ''}: {' + '.join(include)} tables.\n"
        "-- Generated by `python -m backend.database.ddl`; do not edit - change the table definitions and regenerate.\n"
    )
    body = "\n\n".join(statements(dialect_name, schema=schema, include=include))
    return header + "\n" + "\n".join(line.rstrip() for line in body.splitlines()) + "\n"  # SQLAlchemy leaves a space after each comma


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dialect", default="hana", choices=["hana", "sqlite"])
    parser.add_argument("--schema", default=None, help="qualify every table with this schema")
    parser.add_argument("--include", default="state,reference", help="comma-separated: state, reference")
    parser.add_argument("--write", default=None, help="write to this file instead of printing")
    args = parser.parse_args(argv)
    include = tuple(g.strip() for g in args.include.split(",") if g.strip())
    unknown = [g for g in include if g not in GROUPS]
    if unknown:
        parser.error(f"unknown group(s) {unknown}; use state and/or reference")
    text = render(args.dialect, schema=args.schema, include=include)
    if args.write:
        Path(args.write).parent.mkdir(parents=True, exist_ok=True)
        Path(args.write).write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {args.write}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
