"""Generates the SAP HANA implementation package for the core model from `hana_core_spec.py` and the cleaned data.

    python -m backend.database.hana_core            write db/hana/core/
    python -m backend.database.hana_core --check    exit 1 if the checked-in files are not what this would write

Nothing here connects to SAP HANA, deploys anything or modifies a cleaned file. It READS data/cleaned to (1) refuse to write
anything unless every cleaned value fits the column it is declared for (`hana_core_load.preflight`), and (2) compute the expected
row counts and control totals the validation SQL compares against. The files it writes:

    01_create_tables.sql         the 17 tables: types, primary keys, foreign keys, CHECKs (unqualified: they land in the current schema)
    02_create_tables.sql         the same 17 CREATE statements with the target schema written out, and nothing else: paste-and-run
    02_comments.sql              COMMENT ON for every table and column (optional; the data dictionary inside HANA)
    HANA_PREFLIGHT_<SCHEMA>.sql  the first run for one schema: report, create the 17 tables only if no name is taken, verify (no DROP, no load)
    03_validate.sql              the validation scorecards, to run after loading
    99_drop_tables.sql           teardown, children first (DESTRUCTIVE; never run by anything here)
    HANA_DATA_DICTIONARY.csv/.md the dictionary: table, column, type, nullable, key, foreign key, provenance, description
    HANA_LOAD_PLAN.md            what loads where, in what order, expecting how many rows, and what needs approval
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import sys
from dataclasses import dataclass
from pathlib import Path

from backend.database import hana_core_load as load
from backend.database.hana_core_spec import LOAD_ORDER, PROVENANCE_VALUES, TABLES, Table

OUT_DIR = Path("db/hana/core")
HEADER = "Generated by `python -m backend.database.hana_core`; do not edit. Change hana_core_spec.py and regenerate."

DIALECTS = {
    # only three constructs differ; the HANA file uses HANA's own, the SQLite rehearsal the equivalent
    "hana": {"date": lambda s: f"TO_DATE('{s}', 'YYYY-MM-DD')", "month": lambda c: f"MONTH({c})", "next_day": lambda c: f"ADD_DAYS({c}, 1)"},
    "sqlite": {"date": lambda s: f"'{s}'", "month": lambda c: f"CAST(strftime('%m', {c}) AS INTEGER)", "next_day": lambda c: f"date({c}, '+1 day')"},
}


def lit(text: str) -> str:
    return "'" + str(text).replace("'", "''") + "'"


def q(name: str) -> str:
    return f'"{name}"'


# --------------------------------------------------------------------------- facts from the cleaned data
@dataclass
class Facts:
    rows: dict[str, int]
    totals: dict[str, int]
    date_window: tuple[str, str]
    tariff_extreme: int
    tariff_over_100: int
    price_noise: int
    table_provenance: dict[str, str]
    column_provenance: dict[tuple[str, str], str]


def read_facts(data_dir: Path) -> Facts:
    pre = load.preflight(data_dir)
    if not pre.ok:
        raise SystemExit("the cleaned data does not fit the declared model; nothing was written:\n  " + "\n  ".join(pre.errors))

    def collect(table: str, *columns: str) -> dict[str, list]:
        """The named columns of one table, read in a single pass."""
        t = next(t for t in TABLES if t.name == table)
        names = [c.name for c in t.columns]
        position = {c: names.index(c) for c in columns}
        out: dict[str, list] = {c: [] for c in columns}
        for _, row in load.iter_rows(t, data_dir):
            for c, i in position.items():
                out[c].append(row[i])
        return out

    demand = collect("DEMAND", "DATE", "DEMAND_QUANTITY")
    panel = collect("DEMAND_MODELING_PANEL", "DATE", "DEMAND_QUANTITY")
    inventory = collect("INVENTORY", "DATE", "DEMAND_QUANTITY", "OUTBOUND_QUANTITY", "UNFILLED_QUANTITY", "STOCKOUT_FLAG")
    product = collect("PRODUCT", "NET_UNITS", "AVG_UNIT_PRICE_GBP")
    tariff = collect("TARIFF", "TARIFF_RATE_PCT", "QUALITY_FLAG")
    dates = demand["DATE"] + panel["DATE"] + inventory["DATE"]
    totals = {
        "DEMAND.DEMAND_QUANTITY": sum(demand["DEMAND_QUANTITY"]),
        "DEMAND_MODELING_PANEL.DEMAND_QUANTITY": sum(panel["DEMAND_QUANTITY"]),
        "INVENTORY.DEMAND_QUANTITY": sum(inventory["DEMAND_QUANTITY"]),
        "INVENTORY.OUTBOUND_QUANTITY": sum(inventory["OUTBOUND_QUANTITY"]),
        "INVENTORY.UNFILLED_QUANTITY": sum(inventory["UNFILLED_QUANTITY"]),
        "PRODUCT.NET_UNITS": sum(product["NET_UNITS"]),
        "INVENTORY.STOCKOUT_FLAG": sum(1 for v in inventory["STOCKOUT_FLAG"] if v),
    }
    with open(data_dir / "data_dictionary.csv", encoding="utf-8", newline="") as f:
        dictionary = list(csv.DictReader(f))
    column_provenance = {(r["table"].upper(), r["column"].upper()): r["provenance"] for r in dictionary}
    manifest = json.loads((data_dir / "manifest.json").read_text(encoding="utf-8"))["tables"]
    return Facts(
        rows=pre.rows, totals=totals, date_window=(min(dates).isoformat(), max(dates).isoformat()),
        tariff_extreme=sum(1 for flag in tariff["QUALITY_FLAG"] if flag.startswith("EXTREME")), tariff_over_100=sum(1 for v in tariff["TARIFF_RATE_PCT"] if v > 100),
        price_noise=sum(1 for v in product["AVG_UNIT_PRICE_GBP"] if v is not None and len(repr(v).split(".")[-1]) > 4),
        table_provenance={t.name: manifest[t.csv.removesuffix(".csv")]["provenance"] for t in TABLES}, column_provenance=column_provenance,
    )


# --------------------------------------------------------------------------- DDL
def create_table_sql(t: Table, schema: str | None = None, terminator: str = ";") -> str:
    """The CREATE COLUMN TABLE statement. `schema` qualifies the table and every REFERENCES target ("SCHEMA"."TABLE"); by default the
    names are unqualified and land in the current schema. `terminator=""` gives the bare statement, for HANA's EXEC."""
    def name(table: str) -> str:
        return f"{q(schema)}.{q(table)}" if schema else q(table)

    lines = [f"    {q(c.name)} {c.type}{'' if c.nullable else ' NOT NULL'}" for c in t.columns]
    lines.append(f"    CONSTRAINT {q('PK_' + t.name)} PRIMARY KEY ({', '.join(q(c) for c in t.primary_key)})")
    for f in t.foreign_keys:
        lines.append(f"    CONSTRAINT {q(f.name)} FOREIGN KEY ({', '.join(q(c) for c in f.columns)}) REFERENCES {name(f.parent)} ({', '.join(q(c) for c in f.parent_columns)})")
    lines.append(f"    CONSTRAINT {q('CK_' + t.name + '_PROVENANCE')} CHECK ({q('PROVENANCE')} IN ({', '.join(lit(v) for v in PROVENANCE_VALUES)}))")
    for ck in t.checks:
        lines.append(f"    CONSTRAINT {q('CK_' + t.name + '_' + ck.name)} CHECK ({ck.expression})")
    return f"CREATE COLUMN TABLE {name(t.name)} (\n" + ",\n".join(lines) + f"\n){terminator}"


def assert_model_is_sound() -> None:
    """Things that would make HANA reject the DDL or make the model lie, caught before a file is written."""
    by = {t.name: t for t in TABLES}
    names = []
    for t in TABLES:
        assert len({c.name for c in t.columns}) == len(t.columns), f"{t.name}: duplicate column"
        assert all(not next(c for c in t.columns if c.name == k).nullable for k in t.primary_key), f"{t.name}: a primary key column is nullable"
        for f in t.foreign_keys:
            parent = by[f.parent]
            assert LOAD_ORDER.index(f.parent) < LOAD_ORDER.index(t.name), f"{f.name}: parent {f.parent} is created after {t.name}"
            assert tuple(f.parent_columns) == parent.primary_key, f"{f.name}: a foreign key must reference the parent's primary key"
            for child, ref in zip(f.columns, f.parent_columns):
                assert t.column(child).type == parent.column(ref).type, f"{f.name}: {child} and {f.parent}.{ref} have different types"
        names += ["PK_" + t.name, "CK_" + t.name + "_PROVENANCE"] + [f.name for f in t.foreign_keys] + [f"CK_{t.name}_{c.name}" for c in t.checks]
    assert len(names) == len(set(names)), "constraint names must be unique"
    assert all(len(n) <= 127 for n in names), "a constraint name is longer than HANA allows"
    assert not any("PER_WEEK" in c.name for t in TABLES for c in t.columns), "capacity has no time unit"


def render_create_sql() -> str:
    body = "\n\n".join(create_table_sql(t) for t in TABLES)
    return (
        f"-- ResilientSC core data model for SAP HANA Cloud: 17 column tables.\n-- {HEADER}\n--\n"
        "-- Run this in the schema that should own the tables, e.g.:  SET SCHEMA \"<YOUR_SCHEMA>\";\n"
        "-- The names below are unqualified on purpose. Identifiers are QUOTED UPPER CASE: in HANA that is the same identifier as an unquoted one.\n"
        "-- HANA has no CREATE ... IF NOT EXISTS for tables: to start over run 99_drop_tables.sql first.\n"
        "-- Tables are created parents first, so every foreign key finds its parent. NOT YET RUN ON A HANA TENANT.\n\n" + body + "\n"
    )


def render_drop_sql() -> str:
    drops = "\n".join(f"DROP TABLE {q(name)};" for name in reversed(LOAD_ORDER))
    return (
        f"-- TEARDOWN of the 17 core tables. {HEADER}\n--\n-- DESTRUCTIVE: drops the tables and every row in them, in the CURRENT schema. Nothing in this repository runs it.\n"
        "-- Children first, so no foreign key blocks a drop. Check `SELECT CURRENT_SCHEMA FROM DUMMY;` before running.\n\n" + drops + "\n"
    )


PREFLIGHT_SCHEMA = "HACKFEST0119"  # the confirmed target schema: the pre-flight and 02_create_tables.sql are written for it


def render_create_tables_sql(schema: str = PREFLIGHT_SCHEMA) -> str:
    """The 17 CREATE COLUMN TABLE statements and nothing else, every name qualified with `schema`, for pasting into a SQL console that
    may not be in that schema. The same statements as 01_create_tables.sql (a test proves it) with the schema written out: no SET SCHEMA,
    no guard block, no data. Comments avoid semicolons and apostrophes so no client can mistake them for a statement end or a string."""
    body = "\n\n".join(create_table_sql(t, schema=schema) for t in TABLES)
    return (
        f"-- ResilientSC core data model for SAP HANA Cloud: the {len(TABLES)} EMPTY column tables of schema {schema}. Nothing else.\n"
        f"-- {HEADER.replace(';', ',')}\n--\n"
        "-- The same statements as 01_create_tables.sql, with the schema written out on every table and REFERENCES target so nothing depends on\n"
        "-- SET SCHEMA. There is no INSERT, DROP, TRUNCATE, DELETE, ALTER or COMMENT in this file. HANA never replaces a table: if a name already\n"
        "-- exists that CREATE fails and the existing table is left exactly as it is. NOT YET RUN ON A HANA TENANT.\n--\n"
        "-- HOW: SQL console on the Hackfest-DB instance, preference On error = Stop, paste the whole file, Run All (F8).\n"
        "-- Parents are created before children, so every foreign key finds its parent.\n"
        "-- IF IT STOPS PART-WAY: do not run the whole file again. Run STEP 3 of HANA_PREFLIGHT_HACKFEST0119.sql to see which tables exist,\n"
        "-- then select and run only the CREATE statements of the tables that are missing, in file order.\n\n" + body + "\n"
    )


def _literal_rows(aliases: tuple[str, ...], rows: list[tuple]) -> str:
    """A derived table of literals, the HANA way: SELECT ... FROM DUMMY UNION ALL SELECT ... FROM DUMMY. Only the first row names the columns."""
    def literal(v, first: bool) -> str:
        if isinstance(v, int):
            return str(v)
        return f"CAST({lit(v)} AS NVARCHAR(128))" if first else lit(v)  # the first row fixes the column type: make it wide enough for every later row

    out = [("SELECT " if i == 0 else "UNION ALL SELECT ") + ", ".join(f"{literal(v, True)} AS {a}" if i == 0 else literal(v, False) for v, a in zip(row, aliases)) + " FROM DUMMY"
           for i, row in enumerate(rows)]
    return "\n         ".join(out)


def render_preflight_sql(schema: str = PREFLIGHT_SCHEMA) -> str:
    """The first-run script for one schema: report, create the 17 tables only if none of their names is taken, verify.

    It holds no DROP, DELETE, TRUNCATE, ALTER or INSERT and loads nothing. The DDL is 01_create_tables.sql's, with the schema written out
    on every table and REFERENCES target and passed to EXEC inside an anonymous block: HANA has no CREATE ... IF NOT EXISTS, and a block
    that checks first and then creates is the only way to make the whole run refuse instead of half-run. Comments here avoid semicolons and
    apostrophes so no client can mistake them for a statement end or a string."""
    s = lit(schema)
    names = ", ".join(lit(t.name) for t in TABLES)
    order = _literal_rows(("LOAD_ORDER", "TABLE_NAME"), [(i, t.name) for i, t in enumerate(TABLES, 1)])
    n_fk = sum(len(t.foreign_keys) for t in TABLES)
    n_ck = sum(1 + len(t.checks) for t in TABLES)  # every table: the provenance CHECK plus its own
    execs = "\n\n".join(
        f"    -- {i} of {len(TABLES)}: {t.name}\n    EXEC '{create_table_sql(t, schema=schema, terminator='').replace(chr(39), chr(39) * 2)}';" for i, t in enumerate(TABLES, 1)
    )
    columns = _literal_rows(("LOAD_ORDER", "TABLE_NAME", "EXPECTED_COLUMNS"), [(i, t.name, len(t.columns)) for i, t in enumerate(TABLES, 1)])
    types = _literal_rows(
        ("TABLE_NAME", "COLUMN_NAME", "EXPECTED_TYPE"),
        [(t.name, c.name, c.type) for t in TABLES for c in t.columns if c.type.startswith(("DECIMAL", "DOUBLE")) or c.name == "CAPACITY"],
    )
    banner = "-- " + "=" * 96
    return f"""-- HANA PRE-FLIGHT for schema {schema}: can the {len(TABLES)} core tables be created here? Nothing is loaded.
-- {HEADER.replace(';', ',')}
--
-- This file has NO DROP, DELETE, TRUNCATE, ALTER or INSERT. It never replaces an object. NOT YET RUN ON A HANA TENANT.
-- Paste the WHOLE file into a SQL console connected to the Hackfest-DB instance and press Run All (F8). See HANA_PREFLIGHT_INSTRUCTIONS.md.
-- STEP 2 is the only part that changes anything, and it refuses to start if any of the {len(TABLES)} names already exists in {schema}.
-- Every name below is schema-qualified or filtered on {schema}, so the tables cannot land in another schema whatever the session schema is.

SET SCHEMA {q(schema)};

{banner}
-- STEP 1 (read only): who am I, does the schema exist, is any of the {len(TABLES)} names already taken?
{banner}

-- 1a. EXPECTED: one row. TARGET_SCHEMA_EXISTS = 1. SESSION_SCHEMA = {schema}. TARGET_SCHEMA_OWNER shows who owns it and
-- USER_HAS_PRIVILEGES is TRUE when you own it or hold any privilege on it. (Whether you may CREATE there is only proved by STEP 2.)
SELECT CURRENT_USER AS CONNECTED_AS, CURRENT_SCHEMA AS SESSION_SCHEMA, {s} AS TARGET_SCHEMA,
       (SELECT COUNT(*) FROM SYS.SCHEMAS WHERE SCHEMA_NAME = {s}) AS TARGET_SCHEMA_EXISTS,
       (SELECT MAX(SCHEMA_OWNER) FROM SYS.SCHEMAS WHERE SCHEMA_NAME = {s}) AS TARGET_SCHEMA_OWNER,
       (SELECT MAX(HAS_PRIVILEGES) FROM SYS.SCHEMAS WHERE SCHEMA_NAME = {s}) AS USER_HAS_PRIVILEGES
  FROM DUMMY;

-- 1b. EXPECTED: {len(TABLES)} rows, every STATUS = FREE. Any other STATUS means that name is taken and STEP 2 will refuse to create anything.
SELECT E.LOAD_ORDER, E.TABLE_NAME,
       CASE WHEN O.OBJECT_NAME IS NULL THEN 'FREE' ELSE 'ALREADY EXISTS (' || O.OBJECT_TYPE || ')' END AS STATUS
  FROM (
         {order}
       ) E
  LEFT JOIN SYS.OBJECTS O ON O.SCHEMA_NAME = {s} AND O.OBJECT_NAME = E.TABLE_NAME
 ORDER BY E.LOAD_ORDER;

-- 1c. EXPECTED: one row starting with GO.
SELECT CASE WHEN COUNT(*) = 0
            THEN 'GO: all {len(TABLES)} names are free in {schema}, STEP 2 will create the tables'
            ELSE 'STOP: ' || TO_VARCHAR(COUNT(*)) || ' of the {len(TABLES)} names already exist in {schema}, STEP 2 will refuse to create anything'
       END AS PREFLIGHT_VERDICT
  FROM SYS.OBJECTS
 WHERE SCHEMA_NAME = {s} AND OBJECT_NAME IN ({names});

{banner}
-- STEP 2 (creates the {len(TABLES)} tables, all or nothing at the gate): one anonymous block. Parents are created before children.
-- The gates raise error 10001 or 10002 BEFORE anything is created. Once past the gates a failure in a CREATE stops the block. HANA
-- normally commits DDL as it goes, so the tables before the failure may remain and STEP 3 shows which exist. Nothing is dropped or replaced.
-- EXPECTED: the console reports the statement as successfully executed and returns no rows.
{banner}

DO BEGIN
    DECLARE v_found INTEGER;

    -- gate 1: the target schema must exist
    SELECT COUNT(*) INTO v_found FROM SYS.SCHEMAS WHERE SCHEMA_NAME = {s};
    IF :v_found = 0 THEN
        SIGNAL SQL_ERROR_CODE 10001 SET MESSAGE_TEXT = 'PRE-FLIGHT STOPPED: schema {schema} does not exist. Nothing was created.';
    END IF;

    -- gate 2: none of the {len(TABLES)} names may be taken by any object
    SELECT COUNT(*) INTO v_found FROM SYS.OBJECTS WHERE SCHEMA_NAME = {s} AND OBJECT_NAME IN ({names});
    IF :v_found > 0 THEN
        SIGNAL SQL_ERROR_CODE 10002 SET MESSAGE_TEXT = 'PRE-FLIGHT STOPPED: one or more of the {len(TABLES)} table names already exist in {schema}. Nothing was created, dropped or replaced. Run STEP 1 to see which.';
    END IF;

{execs}
END;

{banner}
-- STEP 3 (read only): did the {len(TABLES)} tables come out as specified? Safe to run at any time, also after a failed STEP 2.
{banner}

-- 3a. EXPECTED: {len(TABLES)} rows, every OUTCOME = OK. After a failed STEP 2 the first MISSING row is the table that failed.
SELECT E.LOAD_ORDER, E.TABLE_NAME, E.EXPECTED_COLUMNS, COUNT(C.COLUMN_NAME) AS ACTUAL_COLUMNS,
       CASE WHEN COUNT(C.COLUMN_NAME) = E.EXPECTED_COLUMNS THEN 'OK' WHEN COUNT(C.COLUMN_NAME) = 0 THEN 'MISSING' ELSE 'MISMATCH' END AS OUTCOME
  FROM (
         {columns}
       ) E
  LEFT JOIN SYS.TABLE_COLUMNS C ON C.SCHEMA_NAME = {s} AND C.TABLE_NAME = E.TABLE_NAME
 GROUP BY E.LOAD_ORDER, E.TABLE_NAME, E.EXPECTED_COLUMNS
 ORDER BY E.LOAD_ORDER;

-- 3b. EXPECTED: 4 rows, every OUTCOME = OK ({len(TABLES)} column tables, {len(TABLES)} tables with a primary key, {n_fk} foreign keys, {n_ck} CHECK constraints).
SELECT V.CHECK_NAME, V.ACTUAL, V.EXPECTED, CASE WHEN V.ACTUAL = V.EXPECTED THEN 'OK' ELSE 'MISMATCH' END AS OUTCOME
  FROM (
         SELECT CAST('column tables' AS NVARCHAR(64)) AS CHECK_NAME,
                (SELECT COUNT(*) FROM SYS.TABLES WHERE SCHEMA_NAME = {s} AND TABLE_NAME IN ({names}) AND IS_COLUMN_TABLE = 'TRUE') AS ACTUAL,
                {len(TABLES)} AS EXPECTED FROM DUMMY
         UNION ALL SELECT 'tables with a primary key',
                (SELECT COUNT(DISTINCT TABLE_NAME) FROM SYS.CONSTRAINTS WHERE SCHEMA_NAME = {s} AND TABLE_NAME IN ({names}) AND IS_PRIMARY_KEY = 'TRUE'),
                {len(TABLES)} FROM DUMMY
         UNION ALL SELECT 'foreign keys',
                (SELECT COUNT(DISTINCT CONSTRAINT_NAME) FROM SYS.REFERENTIAL_CONSTRAINTS WHERE SCHEMA_NAME = {s} AND TABLE_NAME IN ({names})),
                {n_fk} FROM DUMMY
         UNION ALL SELECT 'check constraints',
                (SELECT COUNT(DISTINCT CONSTRAINT_NAME) FROM SYS.CONSTRAINTS WHERE SCHEMA_NAME = {s} AND TABLE_NAME IN ({names}) AND CHECK_CONDITION IS NOT NULL),
                {n_ck} FROM DUMMY
       ) V;

-- 3c. EXPECTED: every OUTCOME = OK. Every DECIMAL keeps its precision and scale, every DOUBLE is DOUBLE (TARIFF_RATE_PCT included),
-- and CAPACITY is an INTEGER on SUPPLIER_PRODUCT and ROUTE. If only the ACTUAL_TYPE spelling differs, compare the two columns by eye.
SELECT E.TABLE_NAME, E.COLUMN_NAME, E.EXPECTED_TYPE,
       C.DATA_TYPE_NAME || CASE WHEN C.DATA_TYPE_NAME = 'DECIMAL' THEN '(' || TO_VARCHAR(C.LENGTH) || ',' || TO_VARCHAR(C.SCALE) || ')' ELSE '' END AS ACTUAL_TYPE,
       CASE WHEN C.COLUMN_NAME IS NULL THEN 'MISSING'
            WHEN C.DATA_TYPE_NAME || CASE WHEN C.DATA_TYPE_NAME = 'DECIMAL' THEN '(' || TO_VARCHAR(C.LENGTH) || ',' || TO_VARCHAR(C.SCALE) || ')' ELSE '' END = E.EXPECTED_TYPE THEN 'OK'
            ELSE 'MISMATCH' END AS OUTCOME
  FROM (
         {types}
       ) E
  LEFT JOIN SYS.TABLE_COLUMNS C ON C.SCHEMA_NAME = {s} AND C.TABLE_NAME = E.TABLE_NAME AND C.COLUMN_NAME = E.COLUMN_NAME
 ORDER BY E.TABLE_NAME, E.COLUMN_NAME;
"""


def render_comments_sql() -> str:
    lines = []
    for t in TABLES:
        lines.append(f"COMMENT ON TABLE {q(t.name)} IS {lit(t.description)};")
        lines += [f"COMMENT ON COLUMN {q(t.name)}.{q(c.name)} IS {lit(c.description)};" for c in t.columns]
        lines.append("")
    return (
        f"-- Table and column comments, so the data dictionary lives inside HANA. Optional; run after 01_create_tables.sql. {HEADER}\n\n" + "\n".join(lines)
    )


# --------------------------------------------------------------------------- validation SQL
class Validation:
    """The scorecards. Every row is (CHECK_GROUP, CHECK_NAME, TABLE_NAME, SEVERITY, ACTUAL, EXPECTED, OUTCOME); OUTCOME is PASS when
    ACTUAL = EXPECTED. A violation check expects 0; ERROR failures say FAIL, WARN ones say WARN (a known, documented property)."""

    def __init__(self, facts: Facts, dialect: str = "hana") -> None:
        self.f, self.d = facts, DIALECTS[dialect]
        self.groups: dict[str, list[str]] = {}

    def add(self, group: str, name: str, table: str, tail: str, expected: int = 0, severity: str = "ERROR", agg: str = "COUNT(*)") -> None:
        bad = "FAIL" if severity == "ERROR" else "WARN"
        self.groups.setdefault(group, []).append(
            f"SELECT {lit(group)} AS CHECK_GROUP, {lit(name)} AS CHECK_NAME, {lit(table)} AS TABLE_NAME, {lit(severity)} AS SEVERITY,\n"
            f"       {agg} AS ACTUAL, {expected} AS EXPECTED, CASE WHEN {agg} = {expected} THEN 'PASS' ELSE {lit(bad)} END AS OUTCOME\n  {tail}"
        )

    def build(self) -> dict[str, list[str]]:
        f, d = self.f, self.d
        lo, hi = f.date_window

        for t in TABLES:
            self.add("ROW_COUNT", f"{t.name} has {f.rows[t.name]:,} rows", t.name, f"FROM {q(t.name)}", expected=f.rows[t.name])
        for t in TABLES:
            self.add("NULL_PRIMARY_KEY", f"{t.name}: no NULL in ({', '.join(t.primary_key)})", t.name,
                     f"FROM {q(t.name)} WHERE " + " OR ".join(f"{q(c)} IS NULL" for c in t.primary_key))
        label = {"DEMAND": "duplicate demand keys", "DEMAND_MODELING_PANEL": "duplicate demand keys", "INVENTORY": "duplicate inventory keys",
                 "SUPPLIER_PRODUCT": "supplier-product key uniqueness"}
        for t in TABLES:
            keys = ", ".join(q(c) for c in t.primary_key)
            self.add("DUPLICATE_PRIMARY_KEY", f"{t.name}: {label.get(t.name, 'duplicate keys')} on ({', '.join(t.primary_key)})", t.name,
                     f"FROM (SELECT 1 AS DUPLICATE_KEY FROM {q(t.name)} GROUP BY {keys} HAVING COUNT(*) > 1) D")

        for t in TABLES:
            for fk in t.foreign_keys:
                present = " AND ".join(f"C.{q(c)} IS NOT NULL" for c in fk.columns)
                match = " AND ".join(f"P.{q(pc)} = C.{q(c)}" for c, pc in zip(fk.columns, fk.parent_columns))
                self.add("ORPHAN_FOREIGN_KEY", f"{t.name}.{'+'.join(fk.columns)} -> {fk.parent}.{'+'.join(fk.parent_columns)}", t.name,
                         f"FROM {q(t.name)} C WHERE {present} AND NOT EXISTS (SELECT 1 FROM {q(fk.parent)} P WHERE {match})")
        soft = "(not a declared foreign key) "
        for owner, table in (("SCENARIO_STATE", "SCENARIO_STATE"), ("DISRUPTION_IMPACT", "DISRUPTION_IMPACT")):
            for kind, parent, key in (("ROUTE", "ROUTE", "ROUTE_ID"), ("SUPPLIER", "SUPPLIER", "SUPPLIER_ID")):
                self.add("ORPHAN_FOREIGN_KEY", f"{soft}{owner}.ENTITY_ID of type {kind} -> {parent}.{key}", table,
                         f"FROM {q(table)} S WHERE S.\"ENTITY_TYPE\" = {lit(kind)} AND NOT EXISTS (SELECT 1 FROM {q(parent)} R WHERE R.{q(key)} = S.\"ENTITY_ID\")")
        self.add("ORPHAN_FOREIGN_KEY", f"{soft}DEMAND.LOCATION_ID is the retail label of its COUNTRY_ISO3", "DEMAND",
                 'FROM "DEMAND" D WHERE NOT EXISTS (SELECT 1 FROM "COUNTRY" C WHERE C."ISO3" = D."COUNTRY_ISO3" AND C."RETAIL_LABEL" = D."LOCATION_ID")')
        self.add("ORPHAN_FOREIGN_KEY", f"{soft}DEMAND_MODELING_PANEL.LOCATION_ID -> COUNTRY.RETAIL_LABEL", "DEMAND_MODELING_PANEL",
                 'FROM "DEMAND_MODELING_PANEL" P WHERE NOT EXISTS (SELECT 1 FROM "COUNTRY" C WHERE C."RETAIL_LABEL" = P."LOCATION_ID")')
        for child in ("SUPPLIER_PRODUCT", "INVENTORY"):
            self.add("ORPHAN_FOREIGN_KEY", f"{soft}{child}.PRODUCT_ID is a product of the modeling panel", child,
                     f'FROM {q(child)} C WHERE NOT EXISTS (SELECT 1 FROM "DEMAND_MODELING_PANEL" P WHERE P."PRODUCT_ID" = C."PRODUCT_ID")')

        allowed = ", ".join(lit(v) for v in PROVENANCE_VALUES)
        for t in TABLES:
            self.add("PROVENANCE", f"{t.name}: every row has one of REAL, DERIVED, SYNTHETIC, AUTHORED", t.name,
                     f'FROM {q(t.name)} WHERE "PROVENANCE" IS NULL OR "PROVENANCE" NOT IN ({allowed})')
        for t in TABLES:
            expected = f.table_provenance[t.name]
            self.add("PROVENANCE", f"{t.name}: rows not labelled {expected}, the label the cleaned layer gives this table", t.name,
                     f'FROM {q(t.name)} WHERE "PROVENANCE" <> {lit(expected)}', severity="WARN")

        for t in ("DEMAND", "INVENTORY", "DEMAND_MODELING_PANEL"):
            self.add("DATES", f"{t}: DATE is present and inside the cleaned window {lo} to {hi}", t,
                     f'FROM {q(t)} WHERE "DATE" IS NULL OR "DATE" < {d["date"](lo)} OR "DATE" > {d["date"](hi)}')
        self.add("DATES", f"PRODUCT: sale dates inside {lo} to {hi} and FIRST_SALE_DATE not after LAST_SALE_DATE", "PRODUCT",
                 f'FROM "PRODUCT" WHERE "FIRST_SALE_DATE" < {d["date"](lo)} OR "LAST_SALE_DATE" > {d["date"](hi)} OR "FIRST_SALE_DATE" > "LAST_SALE_DATE"')
        self.add("DATES", "DISRUPTION_EVENT: an event does not end before it starts", "DISRUPTION_EVENT",
                 'FROM "DISRUPTION_EVENT" WHERE "END_TS" IS NOT NULL AND "END_TS" < "START_TS"')
        self.add("DATES", "TARIFF: EFFECTIVE_YEAR is between 1960 and 2100", "TARIFF", 'FROM "TARIFF" WHERE "EFFECTIVE_YEAR" NOT BETWEEN 1960 AND 2100')
        self.add("DATES", "DEMAND_MODELING_PANEL: MONTH agrees with DATE", "DEMAND_MODELING_PANEL",
                 f'FROM "DEMAND_MODELING_PANEL" WHERE "MONTH" <> {d["month"](q("DATE"))}')

        for t in TABLES:  # every CHECK constraint, restated as a query: NOT (rule) is UNKNOWN for NULL, exactly as a CHECK passes on NULL
            for ck in t.checks:
                self.add("QUANTITIES_AND_RANGES", f"{t.name}: {ck.description}", t.name, f"FROM {q(t.name)} WHERE NOT ({ck.expression})")

        self.add("TARIFF_RANGE", "TARIFF: no negative rate", "TARIFF", 'FROM "TARIFF" WHERE "TARIFF_RATE_PCT" < 0')
        self.add("TARIFF_RANGE", "TARIFF: no rate above 50% that is not flagged EXTREME_VALUE", "TARIFF",
                 "FROM \"TARIFF\" WHERE \"TARIFF_RATE_PCT\" > 50 AND \"QUALITY_FLAG\" NOT LIKE 'EXTREME%'")
        self.add("TARIFF_RANGE", "TARIFF: no rate flagged EXTREME_VALUE at or below 50%", "TARIFF",
                 "FROM \"TARIFF\" WHERE \"QUALITY_FLAG\" LIKE 'EXTREME%' AND \"TARIFF_RATE_PCT\" <= 50")
        self.add("TARIFF_RANGE", f"TARIFF: {f.tariff_extreme} rates above 50% are flagged EXTREME_VALUE (source values, kept as published)", "TARIFF",
                 "FROM \"TARIFF\" WHERE \"QUALITY_FLAG\" LIKE 'EXTREME%'", expected=f.tariff_extreme, severity="WARN")
        self.add("TARIFF_RANGE", f"TARIFF: {f.tariff_over_100} rates above 100% (source values, kept as published)", "TARIFF",
                 'FROM "TARIFF" WHERE "TARIFF_RATE_PCT" > 100', expected=f.tariff_over_100, severity="WARN")

        self.add("CONSISTENCY", "INVENTORY: closing = opening + inbound - outbound", "INVENTORY",
                 'FROM "INVENTORY" WHERE "CLOSING_STOCK" <> "OPENING_STOCK" + "INBOUND_QUANTITY" - "OUTBOUND_QUANTITY"')
        self.add("CONSISTENCY", "INVENTORY: outbound + unfilled = demand (no lost sale is hidden)", "INVENTORY",
                 'FROM "INVENTORY" WHERE "OUTBOUND_QUANTITY" + "UNFILLED_QUANTITY" <> "DEMAND_QUANTITY"')
        self.add("CONSISTENCY", "INVENTORY: STOCKOUT_FLAG is set exactly when UNFILLED_QUANTITY > 0", "INVENTORY",
                 'FROM "INVENTORY" WHERE ("STOCKOUT_FLAG" = TRUE AND "UNFILLED_QUANTITY" = 0) OR ("STOCKOUT_FLAG" = FALSE AND "UNFILLED_QUANTITY" > 0)')
        self.add("CONSISTENCY", "INVENTORY: each day opens with the previous day's closing stock", "INVENTORY",
                 f'FROM "INVENTORY" A JOIN "INVENTORY" B ON B."WAREHOUSE_ID" = A."WAREHOUSE_ID" AND B."PRODUCT_ID" = A."PRODUCT_ID" '
                 f'AND B."DATE" = {d["next_day"]("A." + q("DATE"))} WHERE B."OPENING_STOCK" <> A."CLOSING_STOCK"')
        self.add("CONSISTENCY", "INVENTORY: the warehouses' demand adds up to the panel's demand on every product-day", "INVENTORY",
                 'FROM (SELECT "PRODUCT_ID", "DATE", SUM("DEMAND_QUANTITY") AS TOTAL FROM "INVENTORY" GROUP BY "PRODUCT_ID", "DATE") X '
                 'JOIN "DEMAND_MODELING_PANEL" P ON P."PRODUCT_ID" = X."PRODUCT_ID" AND P."DATE" = X."DATE" WHERE P."DEMAND_QUANTITY" <> X.TOTAL')
        self.add("CONSISTENCY", "INVENTORY: complete grid (warehouses x products x days)", "INVENTORY",
                 'FROM (SELECT COUNT(*) AS N, COUNT(DISTINCT "WAREHOUSE_ID") AS W, COUNT(DISTINCT "PRODUCT_ID") AS P, COUNT(DISTINCT "DATE") AS D FROM "INVENTORY") X WHERE X.N <> X.W * X.P * X.D')
        self.add("CONSISTENCY", "DEMAND_MODELING_PANEL: dense calendar (products x days)", "DEMAND_MODELING_PANEL",
                 'FROM (SELECT COUNT(*) AS N, COUNT(DISTINCT "PRODUCT_ID") AS P, COUNT(DISTINCT "DATE") AS D FROM "DEMAND_MODELING_PANEL") X WHERE X.N <> X.P * X.D')
        self.add("CONSISTENCY", "PRODUCT: IS_FORECAST_SERIES marks exactly the panel's products", "PRODUCT",
                 'FROM (SELECT COUNT(*) AS N FROM "PRODUCT" WHERE "IS_FORECAST_SERIES" = TRUE) X WHERE X.N <> (SELECT COUNT(DISTINCT "PRODUCT_ID") FROM "DEMAND_MODELING_PANEL")')
        self.add("CONSISTENCY", "INVENTORY_POLICY: the warehouses' demand shares sum to 1", "INVENTORY_POLICY",
                 'FROM (SELECT SUM("DEMAND_SHARE") AS S FROM "INVENTORY_POLICY") X WHERE ABS(X.S - 1) > 0.0001')
        self.add("CONSISTENCY", "SCENARIO: BASELINE_NORMAL exists", "SCENARIO", 'FROM "SCENARIO" WHERE "SCENARIO_ID" = \'BASELINE_NORMAL\'', expected=1)
        self.add("CONSISTENCY", "SCENARIO_STATE: BASELINE_NORMAL changes nothing (every supplier ACTIVE, every lane NORMAL)", "SCENARIO_STATE",
                 'FROM "SCENARIO_STATE" WHERE "SCENARIO_ID" = \'BASELINE_NORMAL\'')
        self.add("CONSISTENCY", "SUPPLIER: every supplier carries at least one product", "SUPPLIER",
                 'FROM "SUPPLIER" S WHERE NOT EXISTS (SELECT 1 FROM "SUPPLIER_PRODUCT" SP WHERE SP."SUPPLIER_ID" = S."SUPPLIER_ID")')
        self.add("CONSISTENCY", "SUPPLIER_PRODUCT: every product with a supplier has at least two", "SUPPLIER_PRODUCT",
                 'FROM (SELECT "PRODUCT_ID" FROM "SUPPLIER_PRODUCT" GROUP BY "PRODUCT_ID" HAVING COUNT(*) < 2) X')
        self.add("CONSISTENCY", "ROUTE: every SUEZ lane has a CAPE lane between the same ports", "ROUTE",
                 'FROM "ROUTE" S WHERE S."VIA" = \'SUEZ\' AND NOT EXISTS (SELECT 1 FROM "ROUTE" C WHERE C."VIA" = \'CAPE\' '
                 'AND C."ORIGIN_PORT_ID" = S."ORIGIN_PORT_ID" AND C."DESTINATION_PORT_ID" = S."DESTINATION_PORT_ID")')
        self.add("CONSISTENCY", "ROUTE: a CAPE lane is longer than the SUEZ lane between the same ports", "ROUTE",
                 'FROM "ROUTE" S JOIN "ROUTE" C ON C."VIA" = \'CAPE\' AND S."VIA" = \'SUEZ\' AND C."ORIGIN_PORT_ID" = S."ORIGIN_PORT_ID" '
                 'AND C."DESTINATION_PORT_ID" = S."DESTINATION_PORT_ID" WHERE C."DISTANCE_KM" <= S."DISTANCE_KM"')

        for key, total in f.totals.items():
            table, column = key.split(".")
            if column == "STOCKOUT_FLAG":
                self.add("CONTROL_TOTALS", f"{table}: {total:,} stock-out days", table, f'FROM {q(table)} WHERE "STOCKOUT_FLAG" = TRUE', expected=total)
            else:
                self.add("CONTROL_TOTALS", f"{table}: SUM({column}) = {total:,}, as in the cleaned CSV", table, f"FROM {q(table)}", expected=total, agg=f"SUM({q(column)})")
        return self.groups

    def render(self) -> str:
        blocks = []
        for group, selects in self.build().items():
            blocks.append(f"-- {group}\n" + "\nUNION ALL\n".join(selects) + ";")
        return "\n\n".join(blocks) + "\n"


def render_validation_sql(facts: Facts, dialect: str = "hana") -> str:
    intro = (
        f"-- Validation for the core model: run AFTER loading. {HEADER}\n--\n"
        "-- One result set per group. Every row is (CHECK_GROUP, CHECK_NAME, TABLE_NAME, SEVERITY, ACTUAL, EXPECTED, OUTCOME).\n"
        "-- OUTCOME is PASS when ACTUAL = EXPECTED. A FAIL is a real problem. A WARN is a known, documented property of the data\n"
        "-- (e.g. tariff values above 50% that the World Bank publishes); it should still match its EXPECTED count.\n"
        "-- Run with the same current schema as the DDL. Only three constructs are HANA-specific: TO_DATE, MONTH and ADD_DAYS.\n"
        "-- NOT YET RUN ON A HANA TENANT; the same checks, with the SQLite equivalents of those three, are exercised by the tests.\n\n"
    )
    return intro + Validation(facts, dialect).render()


# --------------------------------------------------------------------------- dictionary
def dictionary_rows(facts: Facts) -> list[dict[str, str]]:
    rows = []
    for t in TABLES:
        fk_of = {c: f"{f.parent}.{pc}" for f in t.foreign_keys for c, pc in zip(f.columns, f.parent_columns)}
        for c in t.columns:
            rows.append(
                {
                    "TABLE": t.name, "COLUMN": c.name, "DATA TYPE": c.type, "NULLABLE": "YES" if c.nullable else "NO",
                    "PRIMARY KEY": "YES" if c.name in t.primary_key else "NO", "FOREIGN KEY": fk_of.get(c.name, ""),
                    "PROVENANCE": facts.column_provenance[(t.name, c.name)], "DESCRIPTION": c.description,
                }
            )
    return rows


def render_dictionary_csv(facts: Facts) -> str:
    out = io.StringIO()
    rows = dictionary_rows(facts)
    writer = csv.DictWriter(out, fieldnames=list(rows[0]), lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return out.getvalue()


def render_dictionary_md(facts: Facts) -> str:
    out = ["# ResilientSC core model: data dictionary", "", f"{HEADER} The same content is in `HANA_DATA_DICTIONARY.csv`.", ""]
    for t in TABLES:
        out += [f"## {t.name}", "", t.description, "",
                f"* **Rows expected:** {facts.rows[t.name]:,} (from `{t.csv}`)", f"* **Primary key:** {', '.join(t.primary_key)}"]
        out += [f"* **Foreign key:** `{f.name}`: ({', '.join(f.columns)}) -> {f.parent} ({', '.join(f.parent_columns)})" for f in t.foreign_keys]
        out += [f"* **Check:** `CK_{t.name}_{c.name}`: {c.description}" for c in t.checks]
        out += ["", "| Column | Data type | Null? | PK | FK | Provenance | Description |", "|---|---|---|---|---|---|---|"]
        fk_of = {c: f"{f.parent}.{pc}" for f in t.foreign_keys for c, pc in zip(f.columns, f.parent_columns)}
        for c in t.columns:
            desc = c.description.replace("|", "\\|")
            out.append(f"| {c.name} | {c.type} | {'yes' if c.nullable else 'no'} | {'PK' if c.name in t.primary_key else ''} | {fk_of.get(c.name, '')} | "
                       f"{facts.column_provenance[(t.name, c.name)]} | {desc} |")
        out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------- the load plan
def render_load_plan(facts: Facts) -> str:
    total = sum(facts.rows.values())
    n_fk = sum(len(t.foreign_keys) for t in TABLES)
    order = "\n".join(
        f"| {i} | `{t.csv}` | `{t.name}` | {facts.rows[t.name]:,} | {', '.join(sorted({f.parent for f in t.foreign_keys})) or 'none'} |" for i, t in enumerate(TABLES, 1)
    )
    return f"""# HANA load plan: ResilientSC core model

{HEADER}

**Status: prepared, not run.** Nothing here has connected to SAP HANA, created a table or loaded a row. The source is `data/cleaned/` and is never modified. The SQL is written in the portable subset and rehearsed against an in-memory SQLite database by the tests (`backend/tests/test_hana_core_package.py`); that proves the logic, not HANA's behaviour.

## Files

| File | What it does |
|---|---|
| `01_create_tables.sql` | creates the 17 tables with keys, foreign keys and CHECKs, in the current schema (unqualified names) |
| `02_create_tables.sql` | the same 17 statements with `{PREFLIGHT_SCHEMA}` written out on every name, and nothing else: no data, no `SET SCHEMA`, no guard |
| `02_comments.sql` | optional: table and column comments |
| `HANA_PREFLIGHT_{PREFLIGHT_SCHEMA}.sql` | **run first**: report, create the 17 tables only if none of the names is taken, verify; no DROP, no data (see `HANA_PREFLIGHT_INSTRUCTIONS.md`) |
| `03_validate.sql` | validation scorecards, run after loading |
| `99_drop_tables.sql` | teardown, **destructive**, nothing runs it |
| `HANA_DATA_DICTIONARY.csv` / `.md` | every column: type, nullable, key, foreign key, provenance, description |
| `scripts/load_hana_core.py` | loader (pre-flight, local rehearsal, and, when you choose, the real load) |

## Import order

Parents before children. {total:,} rows in all.

| # | CSV (in `data/cleaned/`) | Table | Expected rows | Depends on |
|---|---|---|---|---|
{order}

## How to load (when approved)

**Before anything connects (once).**

1. The 17 tables exist in `{PREFLIGHT_SCHEMA}` and are empty: created by `02_create_tables.sql` (or STEP 2 of `HANA_PREFLIGHT_{PREFLIGHT_SCHEMA}.sql`, which makes the same tables, never both) and STEP 3 of the pre-flight was all `OK`. The loader creates nothing itself.
2. The SAP drivers are installed in the Python that runs the loader: `py -3.12 -m pip install hdbcli sqlalchemy-hana` (both are listed in `requirements-sap.txt`). The loader says so if they are missing.
3. The connection. `--execute` and `--check-target` read it from `DATABASE_URL` (or a bound HANA instance on BTP), so nothing goes on the command line. It needs four things from your HANA Cloud instance: **host** (`<instance-id>.hana.<region>.hanacloud.ondemand.com`), **port** (443), **database user** and **password**. TLS is mandatory (`encrypt=true`). In PowerShell, this prompts without echoing the password, encodes it (a raw `@ : / # %` would break the URL) and keeps it out of your command history and the process list:

```powershell
$u  = Read-Host "HANA user"
$p  = Read-Host "HANA password" -AsSecureString
$pw = [System.Net.NetworkCredential]::new("", $p).Password
$env:DATABASE_URL = "hana+hdbcli://$([uri]::EscapeDataString($u)):$([uri]::EscapeDataString($pw))@<HOST>:443?encrypt=true&sslValidateCertificate=true"
Remove-Variable pw, p
```

   The `DATABASE_URL` in the project's `.env` is a SQLite file and nothing loads `.env` for you, so it is ignored. A SQLite target is refused. The variable lives only in that PowerShell window.

**The three commands.** Each reads only `data/cleaned/`. None drops a table or changes a CSV.

| # | Command | Connects? | Writes? |
|---|---|---|---|
| 1 | `py -3.12 scripts/load_hana_core.py` | no | no. **Dry run**: reads all 17 CSVs, checks every value, key and foreign key in memory. Expect `pre-flight passed: {total:,} rows`. |
| 2 | `py -3.12 scripts/load_hana_core.py --check-target --schema {PREFLIGHT_SCHEMA}` | yes | **no**. Reports who you are, which of the 17 tables exist, their row counts, and what the load would do. Expect `17 of the 17 model tables exist, 0 rows in them` and `read-only check: nothing was written.` |
| 3 | `py -3.12 scripts/load_hana_core.py --execute --schema {PREFLIGHT_SCHEMA} --validate` | yes | **yes**: {total:,} rows into the 17 tables |

**What command 3 does to `{PREFLIGHT_SCHEMA}`.**

1. Connects, then `SET SCHEMA "{PREFLIGHT_SCHEMA}"`. It stops if the session is not in that schema.
2. Looks before writing: every one of the 17 tables must exist with the model's number of columns and must be **empty**. Otherwise it writes nothing and says which table is the problem.
3. Inserts each CSV in the table order above (parents first), typed exactly as the file holds it, in batches of 5,000, **one transaction per table**: a failure rolls back that table and stops, earlier tables stay.
4. Reads every row count back from HANA with `COUNT(*)` and compares it with the CSV. Every table must say `PASS`.
5. With `--validate`, runs the {sum(len(v) for v in Validation(facts).build().values())} checks of `03_validate.sql`. Every `OUTCOME` must be `PASS`; the `WARN` rows must match their `EXPECTED` counts.

It never creates, drops, truncates or deletes unless you add `--create` or `--truncate` yourself, which this path does not use. If a load stops part-way, fix the cause and add `--resume`: tables that already hold exactly their expected rows are left alone, the empty ones are loaded, and any other table stops the run untouched.

Alternatively the Database Explorer import wizard, table by table in the order above: the CSVs are UTF-8 with a header row, empty field = NULL, booleans `True`/`False`, dates `YYYY-MM-DD`, timestamps `YYYY-MM-DD HH:MM:SS`. That route has not been tried; the script converts every value to a typed Python value itself.

To try the whole load locally first: `py -3.12 scripts/load_hana_core.py --rehearse` (create, load and validate in an in-memory SQLite database; it connects to nothing).

## Validation

`03_validate.sql` has {len(Validation(facts).build())} groups: row counts, NULL primary keys, duplicate primary keys (including the demand, inventory and supplier-product keys), orphan foreign keys (the {n_fk} declared plus the relationships that are deliberately not foreign keys), invalid provenance, invalid dates, negative quantities and ranges (every CHECK constraint restated as a query), tariff ranges, cross-table consistency, and control totals summed from the CSVs.

## Optional and excluded data

Not part of the 17 tables and no DDL is provided for them: `sales_order_line.csv` (about 520k rows; only to recompute demand inside HANA), `tariff_latest.csv` (better as a view over `TARIFF` and `COUNTRY`) and `weather_event_noaa.csv` (69,801 US weather events; recommended to stay in the file layer).

## Decisions that need your approval before loading

1. **Target schema and privileges.** The schema is confirmed as {PREFLIGHT_SCHEMA}. `01_create_tables.sql` stays unqualified (it lands in the current schema). Whether your user may create tables there is what `HANA_PREFLIGHT_{PREFLIGHT_SCHEMA}.sql` tests first.
2. **DECIMAL for fixed-decimal measures.** Costs, distances, coordinates and shares are DECIMAL so they stay exact; HANA returns them as `Decimal`, while the application's `ref_*` contract expects floats, so any `REF_*` view must `CAST(... AS DOUBLE)`.
3. **`PRODUCT.AVG_UNIT_PRICE_GBP` is DOUBLE.** {facts.price_noise} of its {facts.rows['PRODUCT']:,} values carry floating-point noise (more than 4 decimals, e.g. 8.379999999999999). Rounding them would change the cleaned data, which was not to be modified. Accept DOUBLE, or approve a fix in the cleaned layer.
4. **`DEMAND_MODELING_PANEL` keeps all 18 columns**, including the ML lag and rolling features; the application reads 6 of them.
5. **CHECK constraints beyond provenance and non-negativity.** Vocabularies (risk levels, statuses, transport modes, scenario types) come from the codebase and ranges from the data's meaning. They can reject future data that uses a new value; each is one line in `hana_core_spec.py`.
6. **One provenance CHECK for every table** (REAL, DERIVED, SYNTHETIC, AUTHORED), not a narrower set per table. The validation warns when a table holds a label other than the one it was cleaned with.
7. **{n_fk} foreign keys, enforced.** Deliberately not foreign keys: `DEMAND` and `DEMAND_MODELING_PANEL`.`LOCATION_ID` (a text label; the key would have to be the nullable, non-unique `COUNTRY.RETAIL_LABEL`), the polymorphic `ENTITY_ID` columns, `TARIFF.DEST_ISO3` (the sentinel `ANY`) and `PORT.COUNTRY_ISO2`. The panel has no ISO-3 column; adding one would change the cleaned data.
8. **Quoted upper-case identifiers**, so `"DATE"` and `"MONTH"` cannot collide with keywords.
9. **An empty CSV field becomes NULL**, which turns `ROUTE.CHOKEPOINTS` for the rail and air lanes from an empty string into NULL.
10. **Table names follow your list**, not the earlier proposal (`DEMAND`, `INVENTORY`, `DEMAND_MODELING_PANEL`), so none of the application's existing `REF_*` tables or views exists yet.
11. **Capacity and cost have no unit.** `CAPACITY` has no time basis and costs are abstract cost units; the model states neither and invents neither.
12. **Nothing has run on HANA.** `CREATE COLUMN TABLE`, CHECK and FOREIGN KEY constraint syntax, `COMMENT ON`, `TO_DATE`, `MONTH` and `ADD_DAYS` are written from HANA's documented syntax and untested against a tenant.
"""


# --------------------------------------------------------------------------- the package
def build_package(data_dir: Path = load.DEFAULT_DATA_DIR) -> dict[str, str]:
    assert_model_is_sound()
    facts = read_facts(data_dir)
    return {
        "01_create_tables.sql": render_create_sql(),
        "02_create_tables.sql": render_create_tables_sql(),
        "02_comments.sql": render_comments_sql(),
        f"HANA_PREFLIGHT_{PREFLIGHT_SCHEMA}.sql": render_preflight_sql(),
        "03_validate.sql": render_validation_sql(facts),
        "99_drop_tables.sql": render_drop_sql(),
        "HANA_DATA_DICTIONARY.csv": render_dictionary_csv(facts),
        "HANA_DATA_DICTIONARY.md": render_dictionary_md(facts),
        "HANA_LOAD_PLAN.md": render_load_plan(facts),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if the checked-in files are not what this would write")
    parser.add_argument("--out", default=str(OUT_DIR))
    parser.add_argument("--data-dir", default=str(load.DEFAULT_DATA_DIR))
    args = parser.parse_args(argv)
    package = build_package(Path(args.data_dir))
    out = Path(args.out)
    if args.check:
        stale = [name for name, text in package.items() if not (out / name).exists() or (out / name).read_text(encoding="utf-8") != text]
        if stale:
            print(f"out of date: {', '.join(stale)}; run python -m backend.database.hana_core", file=sys.stderr)
            return 1
        print("the HANA package is up to date")
        return 0
    out.mkdir(parents=True, exist_ok=True)
    for name, text in package.items():
        (out / name).write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {out / name} ({len(text.encode('utf-8')) / 1024:.1f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
