#!/usr/bin/env python
"""Self-host the UI's fonts, so the interface looks the same with no network.

The frontend used to load its three text fonts and the Material Symbols icon font from Google Fonts. On
conference wifi that means every icon renders as its ligature *word* ("dashboard", "crisis_alert") and the text
falls back to a system font. This downloads the same font files once into frontend/public/fonts/ and writes
frontend/src/fonts.css with @font-face rules pointing at them. The result is committed, so running this is only
needed to change a font.

    python scripts/fetch_fonts.py

Standard library only. Needs the network once.
"""
from __future__ import annotations

import hashlib
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "frontend" / "public" / "fonts"
CSS_OUT = ROOT / "frontend" / "src" / "fonts.css"
# a browser user agent, or Google serves TTF instead of the woff2 every modern browser wants
UA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"}
TEXT_FONTS = [
    "https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400&display=swap",
    "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&display=swap",
    "https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap",
    "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap",  # the light dashboard theme's face
]
# fixed axes (optical size 24, weight 400, no fill): every icon in the set, 320 KB, and no need to keep a list of the ones used
ICONS = "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&display=block"
KEEP_SUBSETS = {"latin", "latin-ext", "greek"}  # greek: the sigma and mu the interface uses; cyrillic and vietnamese are never shown

ICON_CLASS = """
.material-symbols-outlined {
  font-family: 'Material Symbols Outlined';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
"""


def fetch(url: str) -> bytes:
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as response:
        return response.read()


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def font_faces(css: str) -> list[tuple[str, str]]:
    """(subset comment, @font-face block) pairs, in file order."""
    return re.findall(r"/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, flags=re.S)


def main() -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in FONT_DIR.glob("*.woff2"):
        stale.unlink()
    out: list[str] = ["/* Generated by scripts/fetch_fonts.py — self-hosted, so the UI needs no network. */"]
    saved: dict[str, int] = {}

    for url in TEXT_FONTS:
        for subset, block in font_faces(fetch(url).decode("utf-8")):
            if subset not in KEEP_SUBSETS:
                continue
            family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
            style = re.search(r"font-style:\s*(\w+)", block).group(1)
            src = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
            data = fetch(src)
            digest = hashlib.sha1(data).hexdigest()[:8]
            name = f"{slug(family)}-{style}-{subset}-{digest}.woff2"  # Google serves one variable file for every weight: keep it once
            if name not in saved:
                (FONT_DIR / name).write_bytes(data)
                saved[name] = len(data)
                print(f"  {name:<52} {len(data) / 1024:6.1f} KB")
            out.append(block.replace(src, f"/fonts/{name}"))

    icons = fetch(ICONS).decode("utf-8")
    src = re.search(r"url\((https://[^)]+)\)", icons).group(1)
    data = fetch(src)
    (FONT_DIR / "material-symbols-outlined.woff2").write_bytes(data)
    saved["material-symbols-outlined.woff2"] = len(data)
    block = re.search(r"@font-face\s*\{.*?\}", icons, flags=re.S).group(0)
    out.append(block.replace(src, "/fonts/material-symbols-outlined.woff2"))
    out.append(ICON_CLASS.strip("\n"))
    print(f"  {'material-symbols-outlined.woff2':<52} {len(data) / 1024:6.1f} KB")

    CSS_OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"\n{len(saved)} font files, {sum(saved.values()) / 1024:.0f} KB, and {CSS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
